apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jupyterhub.name }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sqlflow.selectorLabels" . | nindent 6 }}
  {{- if .Values.jupyterhub.strategy }}
  strategy:
{{ toYaml .Values.jupyterhub.strategy | trim | indent 4 }}
    {{ if eq .Values.jupyterhub.strategy.type "Recreate" }}rollingUpdate: null{{ end }}
{{- end }}
  template:
    metadata:
      {{- with .Values.jupyterhub.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sqlflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jupyterhub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.jupyterhub.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.jupyterhub.image.name }}
          securityContext:
            {{- toYaml .Values.jupyterhub.securityContext | nindent 12 }}
          image: {{ .Values.jupyterhub.image.repository }}
          imagePullPolicy: {{ .Values.jupyterhub.image.pullPolicy }}
          env: {{- toYaml .Values.jupyterhub.env | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.jupyterhub.service.servicePort }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          resources:
            {{- toYaml .Values.jupyterhub.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.jupyterhub.persistentVolume.name }}
          hostPath:
            path: {{ .Values.jupyterhub.persistentVolume.mountPath }}
            type: {{ .Values.jupyterhub.persistentVolume.type }}
      {{- with .Values.jupyterhub.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jupyterhub.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.jupyterhub.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}