apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "jupyterhub.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "jupyterhub.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jupyterhub.serviceAccountName" . }}
    namespace: default # as your ServiceAccount is in default namespace