{{- if .Values.serviceAccounts.jupyterhub.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.serviceAccountName" . }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.jupyterhub.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}