apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqlflow.fullname" . }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.sqlflowserver.service.type }}
  ports:
    - port: {{ .Values.sqlflowserver.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sqlflow.selectorLabels" . | nindent 4 }}