
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqlflow-jupyter
rules:
  - apiGroups:
      - extensions
    resourceNames:
      - sqlflow-jupyter
    resources:
      - sqlflow-jupyter
    verbs:
      - use
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
      - events
    verbs:
      - get
      - watch
      - list
      - create
      - delete

