apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jupyterhub.name }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.jupyterhub.service.type }}
  ports:
    - port: {{ .Values.jupyterhub.service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sqlflow.selectorLabels" . | nindent 4 }}