{{- if .Values.serviceAccounts.sqlflowserver.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sqlflowserver.serviceAccountName" . }}
  labels:
    {{- include "sqlflow.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.sqlflowserver.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}